# name: PR Code Review
# on:
#   pull_request:
#     types: [opened, synchronize]

# permissions:            # give the job what it needs
#   pull-requests: write   # lets us post PR comments
#   contents: read

# jobs:
#   review:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - uses: actions/setup-python@v4
#         with:
#           python-version: '3.x'

#       - run: pip install PyGithub

#       - name: Run review script
#         run: python .github/scripts/code_review.py
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub openai

      - name: Run code review script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_AI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python .github/scripts/code_review.py

